language: node_js
node_js: 
- "8.11.1"
before_install:
- npm i -g npm@latest
- npm install 
cache:
directories:
  - "node_modules"
after-script:
- "npm run test:cov"
- "npm install coveralls && cat ./coverage/lcov.info | coveralls"