language: node_js
node_js:
- 8.11.1
cache:
  directories:
    - node_modules
env:
  global:
    - CC_TEST_REPORTER_ID=787a2f89b15c637323c7340d65ec17e898ac44480706b4b4122ea040c2a88f1d
before_install:
- npm install -g mocha
- npm install
script:
- npm run test
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
after_success:
- npm run coveralls
