language: node_js
node_js: 
- "8.11.1"
before_install:
- npm install -g mocha
- npm install 
script: "npm run-script test-travis"
# Send coverage data to Coveralls
after_success:
- npm run coveralls

