language: node_js
node_js: 
- "8.11.1"
before_install:
- npm i -g npm@latest
cache:
directories:
  - "node_modules"
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
after_test:
- npm run coveralls